### ISSUE TITLE
[RFC] Release Plan in 2022 Q2

### ISSUE THREAD

**Issue by henrysun007** [apache/incubator-teaclave#680]
We are releasing v0.5.0 recently. It is the first release since last year. Next we are going to publish releases as planned. At least one release will be published in 2022 Q2. The planned features are listed below:

- [ ] Support the execution service running in Occlum
- [ ] Replace the original RPC with tonic gRPC (#668)
- [ ] Implement all the services asynchronously
- [ ] Generate CI code coverage report automatically in CI
- [ ] Secure platform logger aggregator (#669)
- [ ] Pick valuable features from `cleanroom` branch to `master` branch

 If everything went smoothly, we could work on another release, the possible features are listed below:
- [ ] Multiple task concurrency in the management and execution service
- [ ] Enable access control service
- [ ] Support multiple TEE implementations (#460)

**Comment by henrysun007** [comment]
Generating code coverage report needs to compile code in debug mode. The debug output is too large to fit in one action runner that has only 15GB disk. Therefore, we are not integrating the code coverage report generation in the CI at present.

**Comment by henrysun007** [comment]
Hanlding multiple tasks in one execution service faces isolation issues, so we keep the current single task handling.
